[target.avr-atmega328p.dependencies]
core = { git = "https://github.com/avr-rust/libcore", branch = "rust-26015da0" }

[target.avr-unknown-unknown.dependencies]
core = { git = "https://github.com/avr-rust/libcore", branch = "rust-26015da0" }

